export default function getAllProducts() {
  return [
    {
      id: 'Brownies-Almond-001',
      slug: 'Brownies-Almond',
      name: "Brownies Almond ",
      category: 'Cemilan\ Manis',
      price: 25_000,
      stock: 100,
      imageUrl: '/assets/images/1.png',
      description: "Cemilan manis ini menghadirkan rasa yang lembut dan nikmat, cocok untuk memanjakan lidah Anda. Dengan bahan berkualitas, seperti cokelat premium, karamel lembut, atau gula yang pas, setiap gigitan memberikan kenikmatan yang sulit dilupakan. Cocok untuk menemani waktu santai, minum teh, atau sebagai hadiah manis untuk orang tercinta. Cemilan ini memberikan sentuhan manis dalam setiap momen Anda!",
    },
    {
      id: 'Soes-Kering-001',
      slug: 'Soes-Kering',
      name: "Soes Kering Coklat",
      category: 'Cemilan\ Manis',
      price: 30_000,
      stock: 100,
      imageUrl: '/assets/images/3.png',
      description: 'Cemilan manis ini menghadirkan rasa yang lembut dan nikmat, cocok untuk memanjakan lidah Anda. Dengan bahan berkualitas, seperti cokelat premium, karamel lembut, atau gula yang pas, setiap gigitan memberikan kenikmatan yang sulit dilupakan. Cocok untuk menemani waktu santai, minum teh, atau sebagai hadiah manis untuk orang tercinta. Cemilan ini memberikan sentuhan manis dalam setiap momen Anda!',
    },
    {
      id: 'Pisang-Lumer-002',
      slug: 'Pisang-Lumer',
      name: "Pisang Lumer Coklat",
      category: 'Cemilan\ Manis',
      price: 15_000,
      stock: 5,
      imageUrl: '/assets/images/2.png',
      description: 'Cemilan manis ini menghadirkan rasa yang lembut dan nikmat, cocok untuk memanjakan lidah Anda. Dengan bahan berkualitas, seperti cokelat premium, karamel lembut, atau gula yang pas, setiap gigitan memberikan kenikmatan yang sulit dilupakan. Cocok untuk menemani waktu santai, minum teh, atau sebagai hadiah manis untuk orang tercinta. Cemilan ini memberikan sentuhan manis dalam setiap momen Anda!',
    },
    {
      id: 'Kastangel-001',
      slug: 'Kastangel',
      name: 'Kastangel',
      category: 'Cemilan\ Manis',
      price: 50_000,
      stock: 0,
      imageUrl: '/assets/images/4.png',
      description: "Cemilan manis ini menghadirkan rasa yang lembut dan nikmat, cocok untuk memanjakan lidah Anda. Dengan bahan berkualitas, seperti cokelat premium, karamel lembut, atau gula yang pas, setiap gigitan memberikan kenikmatan yang sulit dilupakan. Cocok untuk menemani waktu santai, minum teh, atau sebagai hadiah manis untuk orang tercinta. Cemilan ini memberikan sentuhan manis dalam setiap momen Anda!",
    },
    {
      id: 'Makaroni-Pedas-001',
      slug: 'Makaroni-Pedas',
      name: 'Makaroni-Pedas',
      category: 'Cemilan\ Pedas',
      price: 20_000,
      stock: 100,
      imageUrl: '/assets/images/5.png',
      description: `Cemilan pedas ini dirancang khusus untuk para pecinta rasa pedas yang menggigit. Dengan bumbu rempah khas dan taburan cabai yang menggoda, setiap gigitannya memberikan sensasi panas di lidah yang memacu semangat. Cocok dinikmati kapan saja, baik saat bersantai, bekerja, atau bersama teman-teman. Rasakan perpaduan pedas yang menyenangkan dengan tekstur yang renyah, membuat Anda sulit berhenti makan!`
    },
    {
      id: 'Basreng-Pedas-001',
      slug: 'Basreng-Pedas',
      name: "Basreng Pedas",
      category: 'Cemilan\ Pedas',
      price: 25_000,
      stock: 100,
      imageUrl: '/assets/images/6.png',
      description: "Cemilan pedas ini dirancang khusus untuk para pecinta rasa pedas yang menggigit. Dengan bumbu rempah khas dan taburan cabai yang menggoda, setiap gigitannya memberikan sensasi panas di lidah yang memacu semangat. Cocok dinikmati kapan saja, baik saat bersantai, bekerja, atau bersama teman-teman. Rasakan perpaduan pedas yang menyenangkan dengan tekstur yang renyah, membuat Anda sulit berhenti makan!"
    },
    {
      id: 'Keripik-Kaca-002',
      slug: 'Keripik-Kaca',
      name: "Keripik Kaca Pedas",
      category: 'Cemilan\ Pedas',
      price: 25_000,
      stock: 5,
      imageUrl: `/assets/images/7.png`,
      description: "Cemilan pedas ini dirancang khusus untuk para pecinta rasa pedas yang menggigit. Dengan bumbu rempah khas dan taburan cabai yang menggoda, setiap gigitannya memberikan sensasi panas di lidah yang memacu semangat. Cocok dinikmati kapan saja, baik saat bersantai, bekerja, atau bersama teman-teman. Rasakan perpaduan pedas yang menyenangkan dengan tekstur yang renyah, membuat Anda sulit berhenti makan!",
    },
    {
      id: 'Cipak-Pedas-003',
      slug: 'Cipak-Pedas',
      name: "Cipak pedas",
      category: 'Cemilan\ Pedas',
      price: 15_000,
      stock: 0,
      imageUrl: `/assets/images/8.png`,
      description: `Cemilan pedas ini dirancang khusus untuk para pecinta rasa pedas yang menggigit. Dengan bumbu rempah khas dan taburan cabai yang menggoda, setiap gigitannya memberikan sensasi panas di lidah yang memacu semangat. Cocok dinikmati kapan saja, baik saat bersantai, bekerja, atau bersama teman-teman. Rasakan perpaduan pedas yang menyenangkan dengan tekstur yang renyah, membuat Anda sulit berhenti makan!`
    },
  ]
}